### ISSUE TITLE
Issues with repacking voices (Demonbane)

### ISSUE THREAD

**Issue by Dudemanguy** [marcussacana/MwareStuff#55]
Thanks a ton for this tool. Unfortunately with specifically the `voice.npk` file (`cg` and `script` work fine as far as I can tell) for Demonbane, I am having problems with repacking the `voice.npk` even when I make no modifications to it at all. There's a mixture of results depending on what exactly I do but either the game is not able to play voices when the line comes up or sometimes it just crashes.

I know this is similar to #30 and #39, so I tried to follow some of the advice there, but unfortunately I was not successful. Here are the two files in the hex editor. The left is the original and the right is the repacked version (but contents unmodified).

![voice_npk](https://github.com/marcussacana/MwareStuff/assets/5105515/6335f3ea-d365-4c44-b3ee-6adb8736bd46)

A thought of mine was that the `SegmentationMode` value is the problem. I am passing `-SG 0`, but it doesn't seem to affect the value. I also noticed the repacked version has a slightly smaller file size for some reason even though the contents should be identical.

If I pass `-SG 1` instead (shown below), the outputted file size is exactly the same as the original and now the initial offset matches. The `SegmentationMode` is still 1 however and it does not work either.
![voice_npk2](https://github.com/marcussacana/MwareStuff/assets/5105515/0b93e2a5-9d2b-4e36-ae9b-d06cb78e7f85)

I tried some various `-MS` values as well, but that didn't seem to change anything about the file. I'm sure I'm doing something wrong here, but I haven't been able to figure it out. Any help would be appreciated.

**Comment by marcussacana** [comment]
Let me ask you to extract the repacked npk and check if any file was different of the original ones, if yes we may have here a repack bug.
Also, there are a param that you can test, the `-MV` can be 1 or 2, try both as well.
The `SegmentationMode`, when 0 means that the file content is fragmented, and the 1 means the file isn't fragmented, this change internally how the engine read the file content but should automatically set to 0 when it needs to be fragmented.
So it will be naturally 1 when the file is not fragmented and that can be even with `-SG 1`, because the segmentation is usually only required for bigger files such as videos, when the file is small there are no need to be fragmented, and in that case the `SegmentationMode` will be 1, that's why it does not change the value when you call with `-SG 1`.

**Comment by Dudemanguy** [comment]
Using `-MV` did not seem to make any difference.

>Let me ask you to extract the repacked npk and check if any file was different of the original ones

I ran sha256sum on all the files in the extraction from the original npk and the extraction from the repacked one. All of the checksums matched and there were no differences. Just to clarify from my earlier post, it's only *some* lines that don't play when using the repacked npk not all of them.

**Comment by marcussacana** [comment]
try change this line
https://github.com/marcussacana/MwareStuff/blob/a282a0e1efa757b4c96aeb529318e46d2fa99750/NPK3Tool/NPK.cs#L165
to:
```
 Entry.SegmentationMode = 0;
 ```
You can build with visual studio or visual code
if works comment it to me implement a proper fix.

**Comment by Dudemanguy** [comment]
Nice, that works. All I have to do is pass `-SG 1`. I checked various scenes and all the lines played. I even replaced one particular ogg file to double check it and it finally worked.

**Comment by marcussacana** [comment]
Fine, tomorrow I will do a proper update to fix it then.

**Comment by marcussacana** [comment]
Fixed with new version, try it if you want.

**Comment by Dudemanguy** [comment]
I can confirm that the new version works. Thanks a lot!
