### ISSUE TITLE
Unable to unpack Chiral Night Rhythm Carnival

### ISSUE THREAD

**Issue by SweetieBell** [marcussacana/MwareStuff#58]
Hello! Sorry if this is a silly question, but I've been trying to unpack Chiral Night Rhythm Carnival recently, and every time I drag the exe onto SRLInjector, a command prompt pops up for maybe a second then immediately disappears. This happens with the npk files on the npk3 tool as well - I've already tried installing .net 3.1, but the issue continues. I assume support for the game isn't available yet because it's a minor release, but if that's not the case and there's a way to get it open with this tool I would hugely appreciate the help! I will gladly send the game files on request if needed. Thank you!!

**Comment by marcussacana** [comment]
You need at least the encryption key, if SRLInjector isn't working in newer games they might changed the engine, not sure since I didn't checked by myself.

**Comment by marcussacana** [comment]
If is a 2017 should be fine then, SRLInjector not working might be some missing thing in your machine like .net framework or .net core.
As well, maybe, the problem is that the game is protected by some DRM (anti-piracy), those type of thing confuses the Key finder and made unable to find the encryption key.
In that case you will need crack the game patching out the DRM, and SRLInjector should works again.

**Comment by marcussacana** [comment]
.Net framework, install around the version 4~4.6.2
